[package]
name = "week_1"
version = "0.1.0"
edition = "2021"
description = "A basic program that uses ownership concepts"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
